# Translations template for cinder.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the cinder project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: cinder 8.0.0.dev112\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-11-04 06:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: cinder/context.py:205
msgid "Unable to get internal tenant context: Missing required config parameters."
msgstr ""

#: cinder/quota_utils.py:56
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume - "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/quota_utils.py:67 cinder/transfer/api.py:191
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumes already consumed)"
msgstr ""

#: cinder/service.py:92
msgid ""
"OSProfiler is enabled.\n"
"It means that person who knows any of hmac_keys that are specified in "
"/etc/cinder/api-paste.ini can trace his requests. \n"
"In real life only operator can read this file so there is no security "
"issue. Note that even if person can trigger profiler, only admin user can"
" retrieve trace information.\n"
"To disable OSprofiler set in cinder.conf:\n"
"[profiler]\n"
"enabled=false"
msgstr ""

#: cinder/service.py:192
#, python-format
msgid ""
"Report interval must be less than service down time. Current config "
"service_down_time: %(service_down_time)s, report_interval for this: "
"service is: %(report_interval)s. Setting global service_down_time to: "
"%(new_down_time)s"
msgstr ""

#: cinder/service.py:263
msgid "Service killed that has no database entry"
msgstr ""

#: cinder/utils.py:912
#, python-format
msgid "Invalid trace flag: %s"
msgstr ""

#: cinder/api/__init__.py:31
msgid ""
"The v1 api is deprecated and will be removed in the Liberty release. You "
"should set enable_v1_api=false and enable_v2_api=true in your cinder.conf"
" file."
msgstr ""

#: cinder/api/extensions.py:276
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:345
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:370
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/backup/api.py:185
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG backup "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/backup/api.py:197
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create backups (%(d_consumed)d "
"backups already consumed)"
msgstr ""

#: cinder/backup/chunkeddriver.py:710
msgid "Error while listing objects, continuing with delete."
msgstr ""

#: cinder/backup/driver.py:212
msgid ""
"Destination volume type is different from source volume type for an "
"encrypted volume. Encrypted backup restore has failed."
msgstr ""

#: cinder/backup/manager.py:747
#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is "
"not verified. Skipping verify."
msgstr ""

#: cinder/backup/drivers/ceph.py:1187
#, python-format
msgid ""
"RBD image for backup %(backup)s of volume %(volume)s not found. Deleting "
"backup metadata."
msgstr ""

#: cinder/common/sqlalchemyutils.py:68
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/consistencygroup/api.py:103
#, python-format
msgid "Availability zone '%s' is invalid"
msgstr ""

#: cinder/db/sqlalchemy/api.py:111
msgid "Use of empty request context is deprecated"
msgstr ""

#: cinder/db/sqlalchemy/api.py:223
#, python-format
msgid "Deadlock detected when running '%(func_name)s': Retrying..."
msgstr ""

#: cinder/db/sqlalchemy/api.py:910
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/image/cache.py:168
#, python-format
msgid "Image-volume cache for host %(host)s does not have enough space (GB)."
msgstr ""

#: cinder/image/glance.py:134
msgid ""
"glance_num_retries shouldn't be a negative value. The number of retries "
"will be set to 0 until this iscorrected in the cinder.conf."
msgstr ""

#: cinder/image/image_utils.py:72
msgid "qemu-img is not installed."
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:79
msgid ""
"config option keymgr.fixed_key has not been defined: some operations may "
"fail unexpectedly"
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:135
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:414
#, python-format
msgid "No weighed hosts found for volume with properties: %s"
msgstr ""

#: cinder/scheduler/host_manager.py:458
#, python-format
msgid "volume service is down. (host: %s)"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:71
#, python-format
msgid ""
"Insufficient free space for volume creation. Total capacity is "
"%(total).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:93
#, python-format
msgid ""
"Insufficient free space for thin provisioning. The ratio of provisioned "
"capacity over total capacity %(provisioned_ratio).2f has exceeded the "
"maximum over subscription ratio %(oversub_ratio).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:115
#, python-format
msgid ""
"Insufficient free space for volume creation on host %(host)s (requested /"
" avail): %(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:61
#, python-format
msgid "Error in filtering function '%(function)s' : '%(error)s' :: failing host"
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:97
#, python-format
msgid "Hint \"%s\" dropped because ExtendedServerAttributes not active in Nova."
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:108
#, python-format
msgid ""
"Hint \"%s\" dropped because Nova did not return enough information. "
"Either Nova policy needs to be changed or a privileged account for Nova "
"should be specified in conf."
msgstr ""

#: cinder/scheduler/weights/goodness.py:54
msgid "Goodness function not set :: defaulting to minimal goodness rating of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:62
#, python-format
msgid ""
"Error in goodness_function function '%(function)s' : '%(error)s' :: "
"Defaulting to a goodness of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:73
#, python-format
msgid ""
"Invalid goodness result.  Result must be between 0 and 100.  Result "
"generated: '%s' :: Defaulting to a goodness of 0"
msgstr ""

#: cinder/transfer/api.py:179 cinder/volume/flows/api/create_volume.py:572
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/api.py:782 cinder/volume/utils.py:706
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)."
msgstr ""

#: cinder/volume/api.py:794 cinder/volume/utils.py:718
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)."
msgstr ""

#: cinder/volume/driver.py:476
#, python-format
msgid "Failed to activate volume copy throttling: %(err)s"
msgstr ""

#: cinder/volume/driver.py:677
#, python-format
msgid ""
"The colon in vendor name was replaced by underscore. Updated vendor name "
"is %(name)s\"."
msgstr ""

#: cinder/volume/driver.py:691
#, python-format
msgid ""
"Vendor unique property \"%(property)s\" must start with vendor prefix "
"with colon \"%(prefix)s\". The property was not registered on "
"capabilities list."
msgstr ""

#: cinder/volume/driver.py:924
#, python-format
msgid ""
"Failed terminating the connection of volume %(volume_id)s, but it is "
"acceptable."
msgstr ""

#: cinder/volume/driver.py:2188 cinder/volume/targets/iscsi.py:158
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/manager.py:213
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:405
#, python-format
msgid "Detected volume stuck in %(curr_status)s status, setting to ERROR."
msgstr ""

#: cinder/volume/manager.py:421
msgid "Detected snapshot stuck in creating status, setting to ERROR."
msgstr ""

#: cinder/volume/manager.py:1029
#, python-format
msgid ""
"Unable to ensure space for image-volume in cache. Will skip creating "
"entry for image %(image)s on host %(host)s."
msgstr ""

#: cinder/volume/manager.py:1039
#, python-format
msgid ""
"Unable to clone image_volume for image %(image_id)s will not create cache"
" entry."
msgstr ""

#: cinder/volume/manager.py:1051
#, python-format
msgid "Failed to create new image-volume cache entry. Error: %(exception)s"
msgstr ""

#: cinder/volume/manager.py:1139
#, python-format
msgid "Registration of image volume URI %(uri)s to image %(image_id)s failed."
msgstr ""

#: cinder/volume/manager.py:1212
#, python-format
msgid "Deleting image in unexpected status: %(image_status)s."
msgstr ""

#: cinder/volume/manager.py:1218
msgid "Image delete encountered an error."
msgstr ""

#: cinder/volume/manager.py:1694
#, python-format
msgid ""
"Failed to migrate volume. The destination volume %(vol)s is not deleted "
"since the source volume may have been deleted."
msgstr ""

#: cinder/volume/manager.py:1849
#, python-format
msgid "Update driver status failed: %(config_group)s is uninitialized."
msgstr ""

#: cinder/volume/qos_specs.py:199
#, python-format
msgid "Failed to associate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:213
#, python-format
msgid "Failed to disassociate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:227
#, python-format
msgid "Failed to disassociate qos specs %s."
msgstr ""

#: cinder/volume/throttling.py:88
#, python-format
msgid "Failed to setup blkio cgroup to throttle the device '%(device)s'."
msgstr ""

#: cinder/volume/utils.py:283
#, python-format
msgid ""
"Incorrect value error: %(blocksize)s, it may indicate that "
"'volume_dd_blocksize' was configured incorrectly. Fall back to default."
msgstr ""

#: cinder/volume/utils.py:693
#, python-format
msgid "Error encountered translating config_string: %(config_string)s to dict"
msgstr ""

#: cinder/volume/drivers/datera.py:111
msgid ""
"Client cert verification and datera_api_token are deprecated in the "
"Datera driver, and will be removed in the Liberty release. Please set the"
" san_login and san_password in your cinder.conf instead."
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:128
#, python-format
msgid "Got disconnected; trying to reconnect. (%s)"
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:512
#, python-format
msgid "snapshot: %s not found, skipping delete operation"
msgstr ""

#: cinder/volume/drivers/eqlx.py:156
msgid ""
"Configuration options eqlx_use_chap, eqlx_chap_login and "
"eqlx_chap_password are deprecated. Use use_chap_auth, chap_username and "
"chap_password respectively for the same."
msgstr ""

#: cinder/volume/drivers/eqlx.py:170
msgid ""
"Configuration option eqlx_cli_timeout is deprecated and will be removed "
"in M release. Use ssh_conn_timeout instead."
msgstr ""

#: cinder/volume/drivers/eqlx.py:449
#, python-format
msgid "Volume %s was not found while trying to delete it."
msgstr ""

#: cinder/volume/drivers/eqlx.py:564
#, python-format
msgid "Volume %s is not found!, it may have been deleted."
msgstr ""

#: cinder/volume/drivers/glusterfs.py:113
#, python-format
msgid "Exception during unmounting %s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:133
#, python-format
msgid "Failed to refresh mounts, reason=%s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:241 cinder/volume/drivers/quobyte.py:189
#: cinder/volume/drivers/remotefs.py:284
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:350
msgid ""
"Fallocate not supported by current version of glusterfs. So falling back "
"to dd."
msgstr ""

#: cinder/volume/drivers/hgst.py:344
msgid "Unable to poll cluster free space."
msgstr ""

#: cinder/volume/drivers/hgst.py:410
#, python-format
msgid "Unable to delete space %(space)s"
msgstr ""

#: cinder/volume/drivers/hgst.py:415
msgid "Attempted to delete a space that's not there."
msgstr ""

#: cinder/volume/drivers/lvm.py:177
#, python-format
msgid "Unable to update stats on non-initialized Volume Group: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:421 cinder/volume/drivers/srb.py:770
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:753
msgid ""
"LVMISCSIDriver is deprecated, you should now just use LVMVolumeDriver and"
" specify iscsi_helper for the target driver you wish to use."
msgstr ""

#: cinder/volume/drivers/lvm.py:770
msgid ""
"LVMISERDriver is deprecated, you should now just use LVMVolumeDriver and "
"specify iscsi_helper for the target driver you wish to use. In order to "
"enable iser, please set iscsi_protocol with the value iser."
msgstr ""

#: cinder/volume/drivers/nfs.py:353 cinder/volume/drivers/remotefs.py:571
#, python-format
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access). This is considered an insecure NAS environment. Please see"
" %s for information on a secure NFS configuration."
msgstr ""

#: cinder/volume/drivers/nfs.py:374 cinder/volume/drivers/remotefs.py:564
#, python-format
msgid ""
"The NAS file operations will be run as root: allowing root level access "
"at the storage backend. This is considered an insecure NAS environment. "
"Please see %s for information on a secure NAS configuration."
msgstr ""

#: cinder/volume/drivers/nfs.py:450
#, python-format
msgid ""
"The option 'nfs_oversub_ratio' is deprecated and will be removed in the "
"Mitaka release.  Please set 'max_over_subscription_ratio = %s' instead."
msgstr ""

#: cinder/volume/drivers/nfs.py:472
#, python-format
msgid ""
"The option 'nfs_used_ratio' is deprecated and will be removed in the "
"Mitaka release.  Please set 'reserved_percentage = %d' instead."
msgstr ""

#: cinder/volume/drivers/nimble.py:167
#, python-format
msgid "Error updating agent-type for volume %s."
msgstr ""

#: cinder/volume/drivers/pure.py:191
#, python-format
msgid "Volume deletion failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:270
#, python-format
msgid "Purity host deletion failed: %(msg)s."
msgstr ""

#: cinder/volume/drivers/pure.py:416
#, python-format
msgid "Unable to delete Protection Group: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:481
#, python-format
msgid "Unable to delete Protection Group Snapshot: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:595
#, python-format
msgid "Unable to rename %(old_name)s, error message: %(error)s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:336
#, python-format
msgid "Exception during mounting %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:396
#, python-format
msgid "Failed to unmount previous mount: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:400
#, python-format
msgid "Unknown error occurred while checking mount point: %s Trying to continue."
msgstr ""

#: cinder/volume/drivers/quobyte.py:419
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/quobyte.py:438
#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:187
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:398
msgid "Unable to get rados pool stats."
msgstr ""

#: cinder/volume/drivers/rbd.py:907
msgid "volume_tmp_dir is now deprecated, please use image_conversion_dir."
msgstr ""

#: cinder/volume/drivers/remotefs.py:369
#, python-format
msgid "%(path)s is being set with open permissions: %(perm)s"
msgstr ""

#: cinder/volume/drivers/remotefs.py:981
#, python-format
msgid "No backing file found for %s, allowing snapshot to be deleted."
msgstr ""

#: cinder/volume/drivers/sheepdog.py:182
#, python-format
msgid "Volume not found. %s"
msgstr ""

#: cinder/volume/drivers/sheepdog.py:234
#, python-format
msgid "Snapshot \"%s\" not found."
msgstr ""

#: cinder/volume/drivers/sheepdog.py:236
#, python-format
msgid "Volume \"%s\" not found."
msgstr ""

#: cinder/volume/drivers/smbfs.py:230 cinder/volume/drivers/ibm/ibmnas.py:289
#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr ""

#: cinder/volume/drivers/solidfire.py:568
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:844
msgid "Requested image is not accessible by current Tenant."
msgstr ""

#: cinder/volume/drivers/srb.py:90
#, python-format
msgid "Retrying failed call to %(func)s, attempt %(attempt)i."
msgstr ""

#: cinder/volume/drivers/srb.py:368
#, python-format
msgid "%s is not an accepted REST server IP address"
msgstr ""

#: cinder/volume/drivers/srb.py:377
msgid "Configuration variable srb_base_urls not set or empty."
msgstr ""

#: cinder/volume/drivers/srb.py:627
#, python-format
msgid "All attempts to recover failed detach of %(volume)s failed."
msgstr ""

#: cinder/volume/drivers/srb.py:687
#, python-format
msgid "Removed volume group %s still appears in vgs."
msgstr ""

#: cinder/volume/drivers/srb.py:881
#, python-format
msgid "Volume %r not found while trying to remove."
msgstr ""

#: cinder/volume/drivers/srb.py:884
#, python-format
msgid "Error while removing export: %r"
msgstr ""

#: cinder/volume/drivers/tintri.py:325
#, python-format
msgid "Exception while creating image %(image_id)s snapshot. Exception: %(exc)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:350
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:441
#, python-format
msgid "Exception during deleting %s"
msgstr ""

#: cinder/volume/drivers/tintri.py:359
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:730
#, python-format
msgid "Destination %s already exists."
msgstr ""

#: cinder/volume/drivers/tintri.py:367
#, python-format
msgid "Exception moving file %(src)s. Message: %(e)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:427
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:500
#, python-format
msgid "Unexpected exception during image cloning in share %s"
msgstr ""

#: cinder/volume/drivers/tintri.py:533
msgid "Unexpected exception while listing used share."
msgstr ""

#: cinder/volume/drivers/xio.py:465
#, python-format
msgid "IOnetworks GET failed (%d)"
msgstr ""

#: cinder/volume/drivers/xio.py:590
#, python-format
msgid "Could not get status for %(name)s (%(status)d)."
msgstr ""

#: cinder/volume/drivers/xio.py:597
msgid "No volume node in XML content."
msgstr ""

#: cinder/volume/drivers/xio.py:604
#, python-format
msgid "No status payload for volume %s."
msgstr ""

#: cinder/volume/drivers/xio.py:692
#, python-format
msgid "Volume %(name)s already presented (%(status)d)!"
msgstr ""

#: cinder/volume/drivers/xio.py:961
#, python-format
msgid "Could not get pool information (%s)!"
msgstr ""

#: cinder/volume/drivers/xio.py:1197
#, python-format
msgid "%s not found!"
msgstr ""

#: cinder/volume/drivers/xio.py:1208
#, python-format
msgid "DELETE call failed for %s!"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:382
#, python-format
msgid "Logout error: %(code)d %(reason)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:574
#, python-format
msgid "Volume initialization failure. (%s)"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:633
#: cinder/volume/drivers/dell/dell_storagecenter_api.py:2192
#, python-format
msgid "Unable to create folder %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:782
#, python-format
msgid "delete_volume: unable to find volume %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:859
#, python-format
msgid "ScServerOperatingSystem GetList return: %(code)d %(reason)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1163
msgid "Inconsistent Luns."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1542
#, python-format
msgid "Unable to create snapshot %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1580
#, python-format
msgid "Unable to find snapshot %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:187
#, python-format
msgid "Unable to locate volume:%s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:660
#, python-format
msgid ""
"Unable to retype Storage Profile, expected to receive current and "
"requested storagetype:storageprofile values. Value received: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:685
msgid ""
"The VMAX plugin only supports Retype. If a pool based migration is "
"necessary this will happen on a Retype From the command line: cinder "
"--os-volume-api-version 2 retype <volumeId> <volumeType> --migration-"
"policy on-demand"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:722
#, python-format
msgid ""
"Failed to migrate: %(volumeName)s from default source storage group for "
"FAST policy: %(sourceFastPolicyName)s. Attempting cleanup... "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:750
#, python-format
msgid ""
"Attempting a rollback of: %(volumeName)s to original pool "
"%(sourcePoolInstanceName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:782
#, python-format
msgid "_migrate_rollback on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:818
#, python-format
msgid "_migrate_cleanup on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1015
#, python-format
msgid ""
"The volume: %(volumename)s was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1108
#, python-format
msgid "Volume: %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1483
#, python-format
msgid ""
"Volume is masked but not to host %(host)s as expected. Returning empty "
"dictionary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2166
#, python-format
msgid ""
"Pre check for deletion. Volume: %(volumeName)s is part of a storage "
"group. Attempting removal from %(storageGroupInstanceNames)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3032
#, python-format
msgid "Volume : %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3305
#, python-format
msgid ""
"The volume: %(volumename)s. was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3746
#, python-format
msgid ""
"Clone failed on V3. Cleaning up the target volume. Clone name: "
"%(cloneName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3957
#, python-format
msgid "FAST is enabled. Policy: %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:140
#, python-format
msgid "Volume: %(volumeName)s Does not belong to storage group %(defaultSgName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:411
msgid "Unable to get storage tiers from tier policy rule."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fc.py:235
#, python-format
msgid "Volume %(volume)s is not in any masking view."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:107
#, python-format
msgid ""
"Volume: %(volumeName)s Does not belong to storage storage group "
"%(defaultSgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1082
#: cinder/volume/drivers/emc/emc_vmax_masking.py:1349
#, python-format
msgid "Unable to find Masking view: %(view)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1251
#, python-format
msgid ""
"No storage group found. Performing rollback on Volume: %(volumeName)s To "
"return it to the default storage group for FAST policy "
"%(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1631
#, python-format
msgid ""
"Volume %(volumeName)s was not first part of the default storage group for"
" the FAST Policy."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1785
#, python-format
msgid ""
"Only one volume remains in storage group %(sgname)s. Driver will attempt "
"cleanup."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1791
#, python-format
msgid "Unable to get masking view %(maskingView)s from storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2106
#, python-format
msgid "No target ports found in masking view %(maskingView)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2160
#: cinder/volume/drivers/emc/emc_vmax_masking.py:2179
#, python-format
msgid "No port group found in masking view %(mv)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_provision_v3.py:624
#, python-format
msgid ""
"Remaining capacity %(remainingCapacityGb)s GBs is determined from SRP "
"pool capacity and not the SLO capacity. Performance may not be what you "
"expect."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1222
#, python-format
msgid "Storage sync name not found for target %(target)s on %(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1263
#, python-format
msgid ""
"Group sync name not found for target group %(target)s on "
"%(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1750
#, python-format
msgid ""
"CreateStorageHardwareID failed. initiator: %(initiator)s, rc=%(rc)d, "
"ret=%(ret)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1770
msgid "Cannot determine the hardware type."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:362
msgid "san_secondary_ip is configured as the same value as san_ip."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:496
#, python-format
msgid "LUN already exists, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:549
#, python-format
msgid "LUN is already deleted, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:622
#, python-format
msgid "LUN %(name)s is already expanded. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:673
#, python-format
msgid "Consistency group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:749
#, python-format
msgid "CG %(cg_name)s does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:753
#, python-format
msgid "CG %(cg_name)s is deleting. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:775
#, python-format
msgid "Cgsnapshot name %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:790
#, python-format
msgid "Snapshot %(name)s for consistency group does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:809
#: cinder/volume/drivers/emc/emc_vnx_cli.py:829
#, python-format
msgid "Snapshot %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:846
#, python-format
msgid "Snapshot %(name)s may deleted already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:853
#, python-format
msgid "Snapshot %(name)s is in use, retry. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:880
#, python-format
msgid "Mount point %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:907
#, python-format
msgid ""
"Snapshot %(snapname)s is attached to snapshot mount point %(mpname)s "
"already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:927
#, python-format
msgid "The specified Snapshot mount point %s is not currently attached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:959
#, python-format
msgid ""
"Migration command may get network timeout. Double check whether migration"
" in fact started successfully. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:971
#, python-format
msgid "Start migration failed. Message: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:974
#, python-format
msgid "Delete temp LUN after migration start failed. LUN: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1117
#, python-format
msgid "Storage group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1133
#, python-format
msgid ""
"Storage group %(name)s doesn't exist, may have already been deleted. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1163
#, python-format
msgid ""
"Host %(host)s has already disconnected from storage group %(sgname)s. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1200
#, python-format
msgid "HLU %(hlu)s has already been removed from %(sgname)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1359
msgid "No array serial number returned, set as unknown."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1393
#, python-format
msgid "Storage Group %s is not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1502
#, python-format
msgid ""
"Invalid iSCSI port %(sp)s-%(port)s-%(vlan)s found in io_port_list, will "
"be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1571
#, python-format
msgid "See unavailable iSCSI target: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1786
msgid ""
"destroy_empty_storage_group: True. Empty storage group will be deleted "
"after volume is detached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1807
msgid "force_delete_lun_in_storagegroup=True"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1814
msgid ""
"ignore_pool_full_threshold: True. LUN creation will still be forced even "
"if the pool full threshold is exceeded."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1834
#, python-format
msgid ""
"The following specified storage pools do not exist: %(unexist)s. This "
"host will only manage the storage pools: %(exist)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1998
msgid ""
"Extra spec key 'storagetype:pool' is obsoleted since driver version "
"5.1.0. This key will be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2033
msgid ""
"Both 'storagetype:prvosioning' and 'provisioning:type' are set in the "
"extra specs, the value of 'provisioning:type' will be used. The key "
"'storagetype:provisioning' may be deprecated in the next release."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2042
msgid ""
"Extra spec key 'storagetype:provisioning' may be deprecated in the next "
"release. It is recommended to use extra spec key 'provisioning:type' "
"instead."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2095
#, python-format
msgid ""
"LUN corresponding to %s is still in some Storage Groups.Try to bring the "
"LUN out of Storage Groups and retry the deletion."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2128
#, python-format
msgid "LUN %(name)s is not ready for extension: %(out)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2149
msgid ""
"Failed to get target_pool_name and target_array_serial. 'location_info' "
"is not in host['capabilities']."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2162
msgid "Error on parsing target_pool_name/target_array_serial."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2176
#, python-format
msgid ""
"Didn't get the pool information of the host %s. Storage assisted "
"Migration is not supported. The host may be using a legacy driver."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2293
#: cinder/volume/drivers/huawei/huawei_driver.py:593
msgid "Storage-assisted migration failed during retype."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2365
#, python-format
msgid "Storage Pool '%(pool)s' is '%(state)s'."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2375
#, python-format
msgid ""
"Maximum number of Pool LUNs, %s, have been created. No more LUN creation "
"can be done."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2479
#, python-format
msgid "LUN %(name)s is not ready for snapshot: %(out)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2743
#, python-format
msgid "LUN with id %(remove_id)s is not present in cg %(cg_name)s, skip it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2838
#, python-format
msgid "Storage Group %s is not found. Create it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2903
#, python-format
msgid "Failed to register %(itor)s to SP%(sp)s port %(portid)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3022
#, python-format
msgid "Failed to extract initiators of %s, so ignore deregistration operation."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3029
#, python-format
msgid "Failed to deregister %(itor)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3289
#, python-format
msgid "Storage Group %s is not found. terminate_connection() is unnecessary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3298
#, python-format
msgid "Volume %(vol)s was not in Storage Group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3320
#, python-format
msgid "Failed to destroy Storage Group %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3326
#, python-format
msgid "Fail to connect host %(host)s back to storage group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3525
#, python-format
msgid ""
"Delete the temporary cgsnapshot %(name)s failed. This temporary "
"cgsnapshot can be deleted manually. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3610
#, python-format
msgid ""
"The source volume is a legacy volume. Create volume in the pool where the"
" source volume %s is created."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3685
#, python-format
msgid "CreateSMPTask.revert: delete mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3705
#, python-format
msgid "AttachSnapTask.revert: detach mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3743
#, python-format
msgid "CreateDestLunTask.revert: delete temp lun %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3811
#, python-format
msgid "CreateSnapshotTask.revert: delete temp cgsnapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3816
#, python-format
msgid "CreateSnapshotTask.revert: delete temp snapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3838
#, python-format
msgid ""
"CopySnapshotTask.revert: delete the copied snapshot %(new_name)s of "
"%(source_name)s."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:136
msgid "No storage pool name or id was found."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:177
msgid "No protection domain name or id was specified in configuration."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:198
msgid "Verify certificate is not set, using default of False."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:637
#, python-format
msgid ""
"Ignoring error in delete volume %s: volume not found due to force delete "
"settings."
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:139
#, python-format
msgid "object %(key)s of type %(typ)s not found, %(err_msg)s"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:516
msgid "terminate_connection: lun map not found"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_common.py:417
#: cinder/volume/drivers/hitachi/hbsd_common.py:423
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1344
#, python-format
msgid "Failed to restart horcm: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_fc.py:181
#, python-format
msgid "Failed to add host group: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:853
#, python-format
msgid "Failed to discard zero page: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1322
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1331
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1338
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1362
#, python-format
msgid "Failed to create pair: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_snm2.py:145
#, python-format
msgid "ldev(%(ldev)d) is already mapped (hlun: %(hlu)d)"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_backend.py:267
#, python-format
msgid "get_evs: %(out)s -- No find for %(fsid)s"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_backend.py:302
#, python-format
msgid "get_fsid: %(out)s -- No info for %(fslabel)s"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_iscsi.py:718
msgid "terminate_conn: provider location empty."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:194
#, python-format
msgid "Can't find lun %s on the array."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:508
#, python-format
msgid "Failure deleting the snapshot %(snapshot_id)s of volume %(volume_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:566
#: cinder/volume/drivers/huawei/huawei_driver.py:568
msgid "Can't find snapshot on the array."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1001
#, python-format
msgid "Lun is not in lungroup. Lun id: %(lun_id)s. lungroup id: %(lungroup_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1007
#: cinder/volume/drivers/huawei/huawei_driver.py:1248
msgid "Can't find lun on the array."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1242
#, python-format
msgid "Lun is not in lungroup. Lun id: %(lun_id)s. Lungroup id: %(lungroup_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/hypermetro.py:262
#, python-format
msgid "Lun is not in lungroup. Lun id: %(lun_id)s, lungroup id: %(lungroup_id)s"
msgstr ""

#: cinder/volume/drivers/huawei/rest_client.py:1274
#: cinder/volume/drivers/huawei/rest_client.py:1283
msgid "Can't find target iqn from rest."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:316
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:353
#, python-format
msgid "Failed to run command: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:757
msgid "_remove_device: invalid properties or device."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:810
#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to any host "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:816
#, python-format
msgid ""
"_unmap_vdisk_from_host: Multiple mappings of volume %(vdisk_name)s found,"
" no host specified."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_fc.py:214
#: cinder/volume/drivers/ibm/flashsystem_iscsi.py:186
#, python-format
msgid "_get_vdisk_map_properties: Did not find a preferred node for vdisk %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:194
msgid ""
"The option storwize_svc_npiv_compatibility_mode will be deprecated and "
"not used. It will be removed in the M release."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:389
msgid "CHAP secret exists for host but CHAP is disabled."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:434
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:491
#, python-format
msgid ""
"Unable to find a preferred node match for node %(node)s in the list of "
"available WWPNs on %(host)s. Using first available."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/__init__.py:807
#, python-format
msgid "Volume %s does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:691
#, python-format
msgid "unmap_vol_from_host: No mapping of volume %(vol_name)s to any host found."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:697
#, python-format
msgid ""
"unmap_vol_from_host: Multiple mappings of volume %(vol_name)s found, no "
"host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:709
#, python-format
msgid ""
"unmap_vol_from_host: No mapping of volume %(vol_name)s to host %(host)s "
"found."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:90
msgid "The MCS Channel is grouped."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:94
msgid "No mapping."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:102
msgid "IQN already existed."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:107
msgid "IQN has been used to create map."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:108
msgid "No such host alias name."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:842
#, python-format
msgid "Volume %(volume_id)s already deleted."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:853
#, python-format
msgid "Volume still %(status)s Cannot delete volume."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1158
msgid "Failed to get Raid Snapshot ID and did not store in snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1171
#, python-format
msgid "Snapshot still %(status)s Cannot delete snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1630
msgid "Failed to get target pool id."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1867
#, python-format
msgid "Volume %(volume_id)s cannot be retyped during attachment."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1874
#, python-format
msgid "Volume %(volume_id)s cannot be retyped because it has snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1897
#, python-format
msgid "The provisioning: %(provisioning)s is not valid."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:66
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:141
#, python-format
msgid "Extra spec %(old)s is obsolete.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:146
#, python-format
msgid "Extra spec %(old)s is deprecated.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:139
#, python-format
msgid "Could not determine root volume name on %s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:320
msgid ""
"The option 'netapp_volume_list' is deprecated and will be removed in the "
"future releases. Please use the option 'netapp_pool_name_search_pattern' "
"instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:366
msgid "Volume refresh job already running. Returning..."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:374
#, python-format
msgid "Error refreshing volume info. Message: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:128
#, python-format
msgid ""
"The \"netapp_size_multiplier\" configuration option is deprecated and "
"will be removed in the Mitaka release. Please set \"reserved_percentage ="
" %d\" instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:234
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:362
#, python-format
msgid ""
"LUN misalignment may occur for current initiator group %(ig_nm)s) with "
"host OS type %(ig_os)s. Please configure initiator group manually "
"according to the type of the host OS."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:314
#, python-format
msgid ""
"Exception while registering image %(image_id)s in cache. Exception: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:383
#, python-format
msgid "Exception during cache cleaning %(share)s. Message - %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:594
msgid "Discover file retries exhausted."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:652
msgid "Unexpected exception while short listing used share."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:738
#, python-format
msgid "Exception moving file %(src)s. Message - %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:229
msgid "No shares found hence skipping ssc refresh."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:524
msgid "ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:536
msgid "refresh stale ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:641
#, python-format
msgid ""
"The user does not have access or sufficient privileges to use all netapp "
"APIs. The following extra_specs will fail or be ignored: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_7mode.py:131
#, python-format
msgid "Error finding LUNs for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:125
#, python-format
msgid "Error mapping LUN. Code :%(code)s, Message: %(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:138
#, python-format
msgid "Error unmapping LUN. Code :%(code)s, Message: %(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:346
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_cmode.py:384
#, python-format
msgid "Rename failure in cleanup of cDOT QOS policy group %(name)s: %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:189
#, python-format
msgid ""
"Production use of \"%(backend)s\" backend requires the Cinder controller "
"to have multipathing properly set up and the configuration option "
"\"%(mpflag)s\" to be set to \"True\"."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:467
msgid "Snapshot volume not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:508
#, python-format
msgid "Failure deleting job %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:511
#, python-format
msgid "Volume copy job for src vol %s not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:526
#, python-format
msgid "Failure deleting temp snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:535
#, python-format
msgid "Volume %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:562
#, python-format
msgid "Snapshot %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:828
#, python-format
msgid "Unable to update host type for host with label %(l)s. %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:833
#, python-format
msgid "Message - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1126
msgid ""
"The option 'netapp_storage_pools' is deprecated and will be removed in "
"the future releases. Please use the option "
"'netapp_pool_name_search_pattern' instead."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1164
#, python-format
msgid "No storage pool found with available capacity %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1204
msgid "Returning as clean tmp vol job already running."
msgstr ""

#: cinder/volume/drivers/prophetstor/dpl_iscsi.py:154
#, python-format
msgid "Cannot get volume status %(exc)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1252
#, python-format
msgid "Flexvisor failed to delete volume %(id)s from the group %(vgid)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1257
#, python-format
msgid ""
"Flexvisor failed to delete volume %(id)s from group %(vgid)s due to "
"%(status)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1426
#, python-format
msgid "Failed to query pool %(id)s status %(ret)d."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:274
#, python-format
msgid ""
"getCPGStatData requires hp3parclient version '%(getcpgstatdata_version)s'"
" version '%(version)s' is installed."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:333
#, python-format
msgid ""
"srstatld requires WSAPI version '%(srstatld_version)s' version "
"'%(version)s' is installed."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:441
#, python-format
msgid "Virtual Volume Set '%s' doesn't exist on array."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:541
#: cinder/volume/drivers/san/hp/hp_3par_common.py:2043
#, python-format
msgid "Delete Snapshot id not found. Removing from cinder: %(id)s Ex: %(msg)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:638
#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:916
#, python-format
msgid "Failed to manage virtual volume %(disp)s due to error during retype."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1072
#, python-format
msgid "3PAR vlun for volume %(name)s not found on host %(host)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1363
msgid ""
"'hp3par:cpg' is not supported as an extra spec in a volume type.  CPG's "
"are chosen by the cinder scheduler, as a pool, from the cinder.conf entry"
" 'hp3par_cpg', which can be a list of CPGs."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:1667
#, python-format
msgid "Delete volume id not found. Removing from cinder: %(id)s Ex: %(msg)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:176
#, python-format
msgid "Invalid IP address format '%s'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:209
#, python-format
msgid ""
"Found invalid iSCSI IP address(s) in configuration option(s) "
"hp3par_iscsi_ips or iscsi_ip_address '%s.'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:342
#, python-format
msgid ""
"iSCSI IP: '%s' was not found in hp3par_iscsi_ips list defined in "
"cinder.conf."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:380
msgid "Least busy iSCSI port not found, using first iSCSI port in list."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:533
msgid ""
"Host exists without CHAP credentials set and has iSCSI attachments but "
"CHAP is enabled. Updating host with new CHAP credentials."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:565
msgid "Host has no CHAP key, but CHAP is enabled."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:569
msgid "No host or VLUNs exist. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:598
msgid "Non-iSCSI VLUN detected."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:602
msgid "No VLUN contained CHAP credentials. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_cliq_proxy.py:87
msgid ""
"The HPLeftHandISCSIDriver CLIQ driver has been DEPRECATED as of the "
"2015.2 release. This driver will be removed in the 2016.1 release. Please"
" use the HPLeftHandISCSIDriver REST based driver instead."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:175
#, python-format
msgid ""
"HPLeftHand API is version %(current)s. A minimum version of %(min)s is "
"needed for manage/unmanage support."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:629
#, python-format
msgid "CHAP secret exists for host %s but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:632
#, python-format
msgid "CHAP is enabled, but server secret not configured on server %s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_lefthand_rest_proxy.py:706
#, python-format
msgid "%s"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:192
#, python-format
msgid "Lun create for %s failed!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_common.py:217
#, python-format
msgid "Lun %s has dependent snapshots, skipping."
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:445
#: cinder/volume/drivers/violin/v6000_iscsi.py:464
msgid "Failed to receive update for total_gb stat!"
msgstr ""

#: cinder/volume/drivers/violin/v6000_fcp.py:452
#: cinder/volume/drivers/violin/v6000_iscsi.py:471
msgid "Failed to receive update for free_gb stat!"
msgstr ""

#: cinder/volume/drivers/vmware/datastore.py:227
#, python-format
msgid "Unable to fetch datastores connected to host %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:530
#, python-format
msgid "Trying to boot from an empty volume: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:708
#, python-format
msgid "Error occurred while deleting temporary disk: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:839
#, python-format
msgid "Error occurred while deleting descriptor: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:872
#, python-format
msgid "Error occurred while deleting backing: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1238
#, python-format
msgid "Volume: %s is in use, can't retype."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1307
#, python-format
msgid ""
"There are no datastores matching new requirements; can't retype volume: "
"%s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1362
#, python-format
msgid ""
"Changing backing: %(backing)s name from %(new_name)s to %(old_name)s "
"failed."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1609
#, python-format
msgid ""
"Cannot undo volume rename; old name was %(old_name)s and new name is "
"%(new_name)s."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:178
msgid "zfssa_initiator_config not found. Using deprecated configuration options."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:183
#, python-format
msgid ""
"zfssa_initiator: %(ini)s wont be used on zfssa_initiator_group= "
"%(inigrp)s."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssarest.py:969
#, python-format
msgid "Property %s already exists."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:286
#, python-format
msgid ""
"Availability zone '%(s_az)s' not found, falling back to "
"'%(s_fallback_az)s'."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:348
msgid "Volume type will be changed to be the same as the source volume."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:585
#, python-format
msgid ""
"Quota %(s_name)s exceeded for %(s_pid)s, tried to create volume "
"(%(d_consumed)d volume(s) already consumed)."
msgstr ""

#: cinder/volume/flows/manager/create_volume.py:681
#, python-format
msgid ""
"Failed to create volume from image-volume cache, will fall back to "
"default behavior. Error: %(exception)s"
msgstr ""

#: cinder/volume/flows/manager/create_volume.py:718
msgid "Unable to get Cinder internal context, will not use image-volume cache."
msgstr ""

#: cinder/volume/targets/cxt.py:131 cinder/volume/targets/tgt.py:166
#, python-format
msgid "Persistence file already exists for volume, found file at: %s"
msgstr ""

#: cinder/volume/targets/cxt.py:196 cinder/volume/targets/tgt.py:257
#, python-format
msgid "Volume path %s does not exist, nothing to remove."
msgstr ""

#: cinder/volume/targets/iet.py:191
#, python-format
msgid ""
"Failed to update %(conf)s for volume id %(vol_id)s after removing iscsi "
"target. %(conf)s does not exist."
msgstr ""

#: cinder/volume/targets/iser.py:28
msgid ""
"ISERTgtAdm is deprecated, you should now just use LVMVolumeDriver and "
"specify iscsi_helper for the target driver you wish to use. In order to "
"enable iser, please set iscsi_protocol=iser with lioadm or tgtadm target "
"helpers."
msgstr ""

#: cinder/volume/targets/lio.py:80
#, python-format
msgid ""
"Failed to save iscsi LIO configuration when modifying volume id: "
"%(vol_id)s."
msgstr ""

#: cinder/volume/targets/tgt.py:84
msgid "Attempting recreate of backing lun..."
msgstr ""

#: cinder/volume/targets/tgt.py:194
#, python-format
msgid "Could not create target because it already exists for volume: %s"
msgstr ""

#: cinder/volume/targets/tgt.py:279
#, python-format
msgid ""
"Failed target removal because target or ACL's couldn't be found for iqn: "
"%s."
msgstr ""

#: cinder/volume/targets/tgt.py:298
msgid "Silent failure of target removal detected, retry...."
msgstr ""

#: cinder/zonemanager/utils.py:79
msgid "Driver didn't return connection info, can't add zone."
msgstr ""

#: cinder/zonemanager/utils.py:104
msgid "Driver didn't return connection info from terminate_connection call."
msgstr ""

#: cinder/zonemanager/drivers/cisco/cisco_fc_zone_client_cli.py:378
#, python-format
msgid "Error running SSH command: %s"
msgstr ""

