# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 11.0.0.0b4.dev52\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-23 14:29+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: glance/scrubber.py:317
#, python-format
msgid ""
"One or more image locations couldn't be scrubbed from backend. Leaving "
"image '%s' in 'pending_delete' status"
msgstr ""

#: glance/api/common.py:170
#, python-format
msgid ""
"User %(user)s attempted to upload an image of unknown size that will "
"exceed the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/common.py:179
#, python-format
msgid ""
"User %(user)s attempted to upload an image of size %(size)d that will "
"exceed the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/v1/images.py:726
#, python-format
msgid ""
"Failed to activate image %s in registry. About to delete image bits from "
"store and update status to 'killed'."
msgstr ""

#: glance/api/v2/images.py:972
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""

#: glance/api/v2/tasks.py:73
#, python-format
msgid "Forbidden to create task. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:111
#, python-format
msgid "Failed to find task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:117
#, python-format
msgid "Forbidden to get task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/artifacts/location.py:126
#, python-format
msgid "Failed to delete blob %s in store from URI"
msgstr ""

#: glance/async/utils.py:62
#, python-format
msgid "An optional task has failed, the failure was: %s"
msgstr ""

#: glance/async/flows/convert.py:68
#, python-format
msgid ""
"The conversion format is None, please add a value for it in the config "
"file for this task to work: %s"
msgstr ""

#: glance/cmd/replicator.py:608
#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, "
"destination is %(slave_value)s)"
msgstr ""

#: glance/cmd/replicator.py:621
#, python-format
msgid "Image %s entirely missing from the destination"
msgstr ""

#: glance/common/store_utils.py:58
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr ""

#: glance/common/wsgi.py:329
#, python-format
msgid "Unrecognised child %s"
msgstr ""

#: glance/common/artifacts/loader.py:125
#, python-format
msgid "Can't load artifact %s: load disabled in config"
msgstr ""

#: glance/common/artifacts/loader.py:151
#, python-format
msgid "Can't load artifact %s: not in available_plugins list"
msgstr ""

#: glance/common/scripts/image_import/main.py:158
#, python-format
msgid "Task %(task_id)s failed with exception %(error)s"
msgstr ""

#: glance/db/simple/api.py:387
#, python-format
msgid "Could not find image %s"
msgstr ""

#: glance/db/simple/api.py:392
msgid "Unable to get deleted image"
msgstr ""

#: glance/db/simple/api.py:396
msgid "Unable to get unowned image"
msgstr ""

#: glance/db/simple/api.py:910
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:915
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:1076
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:76
msgid "Deadlock detected. Retrying..."
msgstr ""

#: glance/db/sqlalchemy/api.py:116
msgid "Attempted to modify image user did not own."
msgstr ""

#: glance/db/sqlalchemy/api.py:331
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:136
msgid "Artifact with the specified type, name and version already exists"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:242
#, python-format
msgid "Artifact with id=%s not found"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:245
#, python-format
msgid "Artifact with id=%s is not accessible"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:445
#, python-format
msgid "Show level %s is not supported in this operation"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:686
#, python-format
msgid ""
"Artifact with the specified type, name and versions already has the "
"direct dependency=%s"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:716
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the direct"
" dependency=%d"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:353 glance/db/sqlalchemy/metadata.py:361
#: glance/db/sqlalchemy/metadata.py:370
#, python-format
msgid "Duplicate entry for values: %s"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/tag.py:37
#, python-format
msgid "Metadata tag not found for id %s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:90
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr ""

#: glance/domain/__init__.py:504
msgid "The `eventlet` executor has been deprecated. Use `taskflow` instead."
msgstr ""

#: glance/image_cache/__init__.py:75
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""

#: glance/image_cache/__init__.py:96
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""

#: glance/image_cache/prefetcher.py:48
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr ""

#: glance/image_cache/prefetcher.py:53
#, python-format
msgid "No metadata found for image '%s'"
msgstr ""

#: glance/image_cache/prefetcher.py:81
msgid "Failed to successfully cache all images in queue."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:332
#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:458
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:495
#: glance/image_cache/drivers/xattr.py:445
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr ""

#: glance/registry/api/v1/images.py:127
#, python-format
msgid "Invalid marker. Image %(id)s could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:132 glance/registry/api/v1/members.py:77
#: glance/registry/api/v1/members.py:112 glance/registry/api/v1/members.py:231
#: glance/registry/api/v1/members.py:296
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr ""

#: glance/registry/api/v1/members.py:119 glance/registry/api/v1/members.py:238
#: glance/registry/api/v1/members.py:303
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:130 glance/registry/api/v1/members.py:147
#: glance/registry/api/v1/members.py:251
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:342
#, python-format
msgid "Member %(id)s not found"
msgstr ""

