# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: keystone 8.0.0.0rc2.dev1\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2015-10-01 06:09+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: keystone/exception.py:78
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:87
#, python-format
msgid "Cannot create an endpoint with an invalid URL: %(url)s"
msgstr ""

#: keystone/exception.py:94
#, python-format
msgid "%(detail)s"
msgstr ""

#: keystone/exception.py:98
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:107
msgid ""
"The 'expires_at' must not be before now. The server could not comply with"
" the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."
msgstr ""

#: keystone/exception.py:116
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:122
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:132
#, python-format
msgid ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."
msgstr ""

#: keystone/exception.py:139
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server "
"could not comply with the request because the password is invalid."
msgstr ""

#: keystone/exception.py:147
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions "
"have associated endpoints."
msgstr ""

#: keystone/exception.py:154
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:163
msgid "(Disable debug mode to suppress these details.)"
msgstr ""

#: keystone/exception.py:168
#, python-format
msgid "%(message)s %(amendment)s"
msgstr ""

#: keystone/exception.py:176
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:182
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:190
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:195
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:203
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:211
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:218
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr ""

#: keystone/exception.py:223
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target "
"%(target)s"
msgstr ""

#: keystone/exception.py:228
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in "
"question is %(group_id)s, user is %(user_id)s"
msgstr ""

#: keystone/exception.py:234
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service "
"or Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, "
"Service: %(service_id)s, Region: %(region_id)s"
msgstr ""

#: keystone/exception.py:241
#, python-format
msgid "Invalid domain specific configuration: %(reason)s"
msgstr ""

#: keystone/exception.py:245
#, python-format
msgid "Could not find: %(target)s"
msgstr ""

#: keystone/exception.py:251
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr ""

#: keystone/exception.py:258
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:263
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr ""

#: keystone/exception.py:267
msgid "Could not find policy association"
msgstr ""

#: keystone/exception.py:271
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr ""

#: keystone/exception.py:275
#, python-format
msgid ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"
msgstr ""

#: keystone/exception.py:281
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr ""

#: keystone/exception.py:285
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr ""

#: keystone/exception.py:289
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:293
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr ""

#: keystone/exception.py:297
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr ""

#: keystone/exception.py:301
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr ""

#: keystone/exception.py:305
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr ""

#: keystone/exception.py:309
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr ""

#: keystone/exception.py:313
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr ""

#: keystone/exception.py:317
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:321
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:325
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr ""

#: keystone/exception.py:329
#, python-format
msgid "Could not find version: %(version)s"
msgstr ""

#: keystone/exception.py:333
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr ""

#: keystone/exception.py:337
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr ""

#: keystone/exception.py:341
#, python-format
msgid "Could not find Service Provider: %(sp_id)s"
msgstr ""

#: keystone/exception.py:345
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:356
#, python-format
msgid ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"
msgstr ""

#: keystone/exception.py:368
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr ""

#: keystone/exception.py:376
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:379
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""

#: keystone/exception.py:402
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr ""

#: keystone/exception.py:407
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:413
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:418
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:423
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr ""

#: keystone/exception.py:427
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:434
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:441
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:448
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:453
msgid ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap "
"one."
msgstr ""

#: keystone/exception.py:458
#, python-format
msgid ""
"The Keystone domain-specific configuration has specified more than one "
"SQL driver (only one is permitted): %(source)s."
msgstr ""

#: keystone/exception.py:465
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/exception.py:472
msgid "Token version is unrecognizable or unsupported."
msgstr ""

#: keystone/exception.py:477
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not "
"have xmlsec1 installed, or this is the result of misconfiguration. Reason"
" %(reason)s"
msgstr ""

#: keystone/exception.py:485
msgid ""
"No Authorization headers found, cannot proceed with OAuth related calls, "
"if running under HTTPd or Apache, ensure WSGIPassAuthorization is set to "
"On."
msgstr ""

#: keystone/exception.py:493
#, python-format
msgid ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."
msgstr ""

#: keystone/notifications.py:274
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:283
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/assignment/controllers.py:99 keystone/identity/controllers.py:71
#: keystone/resource/controllers.py:88
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:155
#: keystone/assignment/controllers.py:174
msgid "User roles not supported: tenant_id required"
msgstr ""

#: keystone/assignment/controllers.py:338
#: keystone/assignment/controllers.py:579
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:341
msgid "Specify one of domain or project"
msgstr ""

#: keystone/assignment/controllers.py:346
#: keystone/assignment/controllers.py:584
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/controllers.py:349
msgid "Specify one of user or group"
msgstr ""

#: keystone/assignment/controllers.py:568
msgid "Combining effective and group filter will always result in an empty list."
msgstr ""

#: keystone/assignment/controllers.py:573
msgid ""
"Combining effective, domain and inherited filters will always result in "
"an empty list."
msgstr ""

#: keystone/assignment/core.py:198
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/core.py:873
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/assignment/core.py:875
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/assignment/core.py:877
msgid "Unknown Target"
msgstr ""

#: keystone/assignment/backends/ldap.py:91
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:397
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:403
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/backends/ldap.py:418
#: keystone/assignment/backends/sql.py:334
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/backends/sql.py:410
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/assignment/role_backends/ldap.py:61 keystone/catalog/core.py:135
#: keystone/common/ldap/core.py:1400 keystone/resource/backends/ldap.py:170
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/assignment/role_backends/ldap.py:69
#: keystone/common/ldap/core.py:1390
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/assignment/role_backends/ldap.py:119
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/auth/controllers.py:118
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has "
"conflicting values %(new)s and %(old)s"
msgstr ""

#: keystone/auth/controllers.py:344 keystone/middleware/core.py:227
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:347
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:350
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:520
msgid "User not found"
msgstr ""

#: keystone/auth/controllers.py:624
msgid "A project-scoped token is required to produce a service catalog."
msgstr ""

#: keystone/auth/plugins/external.py:42
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:52
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/external.py:100
msgid "auth_type is not Negotiate"
msgstr ""

#: keystone/auth/plugins/mapped.py:239
msgid ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must "
"be set."
msgstr ""

#: keystone/auth/plugins/oauth1.py:51
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:65
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:45
msgid "Invalid username or password"
msgstr ""

#: keystone/auth/plugins/token.py:70 keystone/token/controllers.py:162
msgid "rescope a scoped token"
msgstr ""

#: keystone/catalog/controllers.py:175
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/cmd/cli.py:286
msgid "At least one option must be provided"
msgstr ""

#: keystone/cmd/cli.py:293
msgid "--all option cannot be mixed with other options"
msgstr ""

#: keystone/cmd/cli.py:300
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr ""

#: keystone/cmd/cli.py:355 keystone/tests/unit/test_cli.py:215
msgid "At least one option must be provided, use either --all or --domain-name"
msgstr ""

#: keystone/cmd/cli.py:361 keystone/tests/unit/test_cli.py:231
msgid "The --all option cannot be used with the --domain-name option"
msgstr ""

#: keystone/cmd/cli.py:387 keystone/tests/unit/test_cli.py:248
#, python-format
msgid ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."
msgstr ""

#: keystone/cmd/cli.py:395 keystone/tests/unit/test_cli.py:189
#, python-format
msgid ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."
msgstr ""

#: keystone/cmd/cli.py:409
#, python-format
msgid "Error parsing configuration file for domain: %(domain)s, file: %(file)s."
msgstr ""

#: keystone/cmd/cli.py:442
#, python-format
msgid ""
"To get a more detailed information on this error, re-run this command for"
" the specific domain, i.e.: keystone-manage domain_config_upload "
"--domain-name %s"
msgstr ""

#: keystone/cmd/cli.py:460
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr ""

#: keystone/cmd/cli.py:493
msgid ""
"Unable to access the keystone database, please check it is configured "
"correctly."
msgstr ""

#: keystone/cmd/cli.py:559
#, python-format
msgid "Error while parsing rules %(path)s: %(err)s"
msgstr ""

#: keystone/cmd/cli.py:568
#, python-format
msgid "Error while opening file %(path)s: %(err)s"
msgstr ""

#: keystone/cmd/cli.py:578
#, python-format
msgid "Error while parsing line: '%(line)s': %(err)s"
msgstr ""

#: keystone/common/authorization.py:57 keystone/common/wsgi.py:66
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr ""

#: keystone/common/base64utils.py:71
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:220
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:224
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:230
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:249 keystone/common/base64utils.py:270
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/common/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/common/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/common/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/common/controller.py:230 keystone/common/controller.py:246
#: keystone/token/providers/common.py:638
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/common/controller.py:329 keystone/common/controller.py:358
#: keystone/identity/core.py:596 keystone/resource/core.py:788
#: keystone/resource/backends/ldap.py:66 keystone/resource/backends/ldap.py:74
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/common/controller.py:371
msgid "Marker could not be found"
msgstr ""

#: keystone/common/controller.py:382
msgid "Invalid limit value"
msgstr ""

#: keystone/common/controller.py:690
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/dependency.py:64
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr ""

#: keystone/common/json_home.py:76
#, python-format
msgid "Unexpected status requested for JSON Home response, %s"
msgstr ""

#: keystone/common/tokenless_auth.py:74
msgid "Neither Project Domain ID nor Project Domain Name was provided."
msgstr ""

#: keystone/common/tokenless_auth.py:166
msgid ""
"User auth cannot be built due to missing either user id, or user name "
"with domain id, or user name with domain name."
msgstr ""

#: keystone/common/utils.py:166 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/wsgi.py:206
msgid "Query string is not UTF-8 encoded"
msgstr ""

#: keystone/common/wsgi.py:343
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:355
#, python-format
msgid "%s field(s) cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:566
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/_memcache_pool.py:124
#, python-format
msgid "Unable to get a connection from pool id %(id)s after %(seconds)s seconds."
msgstr ""

#: keystone/common/cache/core.py:132
msgid "region not type dogpile.cache.CacheRegion"
msgstr ""

#: keystone/common/cache/backends/mongo.py:231
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:236
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:241
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:252
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:260
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:275
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:301
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:310
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/kvs/core.py:70
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:105
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:144
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:197
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:352
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:356
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:69
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:185
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:193
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:203
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:215
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:588
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:593
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:603
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:615
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:1325
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr ""

#: keystone/common/ldap/core.py:1369
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:1374
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:1379
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:1522
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by "
"configuration."
msgstr ""

#: keystone/common/ldap/core.py:1533
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:1620
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr ""

#: keystone/common/sql/core.py:219
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/core.py:445
msgid "Duplicate Entry"
msgstr ""

#: keystone/common/sql/core.py:461
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr ""

#: keystone/common/sql/migration_helpers.py:171
#: keystone/common/sql/migration_helpers.py:213
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/common/validation/__init__.py:45
#, python-format
msgid ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."
msgstr ""

#: keystone/common/validation/validators.py:54
#, python-format
msgid "Invalid input for field '%(path)s'. The value is '%(value)s'."
msgstr ""

#: keystone/contrib/ec2/controllers.py:324
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:352
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:70
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:181
msgid "Endpoint Group Project Association not found"
msgstr ""

#: keystone/contrib/federation/controllers.py:268
msgid "Request must have an origin query parameter"
msgstr ""

#: keystone/contrib/federation/controllers.py:273
#, python-format
msgid "%(host)s is not a trusted dashboard host"
msgstr ""

#: keystone/contrib/federation/controllers.py:304
msgid "Missing entity ID from environment"
msgstr ""

#: keystone/contrib/federation/controllers.py:353
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr ""

#: keystone/contrib/federation/idp.py:477
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr ""

#: keystone/contrib/federation/idp.py:544
msgid "Ensure configuration option idp_entity_id is set."
msgstr ""

#: keystone/contrib/federation/idp.py:547
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr ""

#: keystone/contrib/federation/idp.py:567
msgid ""
"idp_contact_type must be one of: [technical, other, support, "
"administrative or billing."
msgstr ""

#: keystone/contrib/federation/utils.py:177
msgid "Federation token is expired"
msgstr ""

#: keystone/contrib/federation/utils.py:230
msgid "Could not find Identity Provider identifier in environment"
msgstr ""

#: keystone/contrib/federation/utils.py:234
msgid ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."
msgstr ""

#: keystone/contrib/federation/utils.py:522
#, python-format
msgid "User type %s not supported"
msgstr ""

#: keystone/contrib/federation/utils.py:557
#, python-format
msgid ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords "
"must be specified."
msgstr ""

#: keystone/contrib/federation/utils.py:766
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr ""

#: keystone/contrib/federation/utils.py:774
#, python-format
msgid "Service Provider %(sp)s is disabled"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:96
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:128
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:189
#: keystone/contrib/oauth1/backends/sql.py:270
msgid "User IDs do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:196
msgid "Could not find role"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:245
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:296
#: keystone/contrib/oauth1/controllers.py:374
msgid "Request token is expired"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:310
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:314
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:318
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:322
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:326
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:363
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:390
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:403
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:186
msgid "Request token not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:250
msgid "Access token not found"
msgstr ""

#: keystone/contrib/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/contrib/revoke/core.py:159
msgid ""
"The revoke call must not have both domain_id and project_id. This is a "
"bug in the Keystone server. The current request is aborted."
msgstr ""

#: keystone/contrib/revoke/core.py:227 keystone/token/provider.py:197
#: keystone/token/provider.py:221 keystone/token/provider.py:287
#: keystone/token/provider.py:294
msgid "Failed to validate token"
msgstr ""

#: keystone/endpoint_policy/core.py:261
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr ""

#: keystone/identity/controllers.py:74
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/identity/controllers.py:100
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/core.py:127
#, python-format
msgid "Database at /domains/%s/config"
msgstr ""

#: keystone/identity/core.py:271
#, python-format
msgid "Config API entity at /domains/%s/config"
msgstr ""

#: keystone/identity/core.py:277
#, python-format
msgid ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, "
"the last  domain that appears to have had it is %(last_domain)s, giving "
"up"
msgstr ""

#: keystone/identity/core.py:451 keystone/identity/backends/ldap.py:58
#: keystone/identity/backends/ldap.py:60 keystone/identity/backends/ldap.py:66
#: keystone/identity/backends/ldap.py:68 keystone/identity/backends/sql.py:104
#: keystone/identity/backends/sql.py:106
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/core.py:861
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/identity/core.py:903
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/ldap.py:98
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:187 keystone/identity/backends/sql.py:188
#: keystone/identity/backends/sql.py:206
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr ""

#: keystone/identity/backends/ldap.py:338
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/models/token_model.py:61
msgid "Found invalid token: scoped to both project and domain."
msgstr ""

#: keystone/resource/controllers.py:218
msgid "The creation of projects acting as domains is not allowed yet."
msgstr ""

#: keystone/resource/controllers.py:252
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same "
"time."
msgstr ""

#: keystone/resource/controllers.py:258
msgid ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same "
"time."
msgstr ""

#: keystone/resource/core.py:81
#, python-format
msgid "max hierarchy depth reached for %s branch."
msgstr ""

#: keystone/resource/core.py:100
msgid "cannot create a project within a different domain than its parents."
msgstr ""

#: keystone/resource/core.py:104
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr ""

#: keystone/resource/core.py:126
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/resource/core.py:143
#, python-format
msgid "Domain cannot be named %s"
msgstr ""

#: keystone/resource/core.py:146
#, python-format
msgid "Domain cannot have ID %s"
msgstr ""

#: keystone/resource/core.py:158
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/resource/core.py:178
#, python-format
msgid "cannot enable project %s since it has disabled parents"
msgstr ""

#: keystone/resource/core.py:186
#, python-format
msgid "cannot disable project %s since its subtree contains enabled projects"
msgstr ""

#: keystone/resource/core.py:197
msgid "Update of `parent_id` is not allowed."
msgstr ""

#: keystone/resource/core.py:202
msgid "Update of `is_domain` is not allowed."
msgstr ""

#: keystone/resource/core.py:229
#, python-format
msgid "cannot delete the project %s since it is not a leaf in the hierarchy."
msgstr ""

#: keystone/resource/core.py:256
msgid "Project field is required and cannot be empty."
msgstr ""

#: keystone/resource/core.py:392
msgid "Multiple domains are not supported"
msgstr ""

#: keystone/resource/core.py:445
msgid "delete the default domain"
msgstr ""

#: keystone/resource/core.py:456
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/resource/core.py:876
msgid "No options specified"
msgstr ""

#: keystone/resource/core.py:882
#, python-format
msgid ""
"The value of group %(group)s specified in the config should be a "
"dictionary of options"
msgstr ""

#: keystone/resource/core.py:906
#, python-format
msgid ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"
msgstr ""

#: keystone/resource/core.py:913
#, python-format
msgid "Group %(group)s is not supported for domain specific configurations"
msgstr ""

#: keystone/resource/core.py:920
#, python-format
msgid ""
"Option %(option)s in group %(group)s is not supported for domain specific"
" configurations"
msgstr ""

#: keystone/resource/core.py:973
msgid "An unexpected error occurred when retrieving domain configs"
msgstr ""

#: keystone/resource/core.py:1052 keystone/resource/core.py:1136
#: keystone/resource/core.py:1207 keystone/resource/config_backends/sql.py:76
#, python-format
msgid "option %(option)s in group %(group)s"
msgstr ""

#: keystone/resource/core.py:1055 keystone/resource/core.py:1141
#: keystone/resource/core.py:1203
#, python-format
msgid "group %(group)s"
msgstr ""

#: keystone/resource/core.py:1057
msgid "any options"
msgstr ""

#: keystone/resource/core.py:1101
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"
msgstr ""

#: keystone/resource/core.py:1106
#, python-format
msgid ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"
msgstr ""

#: keystone/resource/core.py:1115
#, python-format
msgid ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"
msgstr ""

#: keystone/resource/core.py:1122
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, but config "
"provided contains option %(option_other)s instead"
msgstr ""

#: keystone/resource/backends/ldap.py:88
msgid "LDAP does not support projects with is_domain flag enabled"
msgstr ""

#: keystone/resource/backends/ldap.py:172
#: keystone/resource/backends/ldap.py:180
#: keystone/resource/backends/ldap.py:184
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/server/eventlet.py:77
msgid ""
"Running keystone via eventlet is deprecated as of Kilo in favor of "
"running in a WSGI server (e.g. mod_wsgi). Support for keystone under "
"eventlet will be removed in the \"M\"-Release."
msgstr ""

#: keystone/server/eventlet.py:90
#, python-format
msgid "Failed to start the %(name)s server"
msgstr ""

#: keystone/token/controllers.py:391
#, python-format
msgid "Project ID not found: %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:395
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:414 keystone/token/controllers.py:417
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/providers/common.py:53
msgid "Domains are not supported by the v2 API. Please use the v3 API instead."
msgstr ""

#: keystone/token/providers/common.py:63
#, python-format
msgid ""
"Project not found in the default domain (please use the v3 API instead): "
"%s"
msgstr ""

#: keystone/token/providers/common.py:82
#, python-format
msgid "User not found in the default domain (please use the v3 API instead): %s"
msgstr ""

#: keystone/token/providers/common.py:299
#: keystone/token/providers/common.py:404
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:304
#: keystone/token/providers/common.py:409
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:331
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:395
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:456
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr ""

#: keystone/token/providers/common.py:484
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:553
msgid "The configured token provider does not support bind authentication."
msgstr ""

#: keystone/token/providers/common.py:628
msgid ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"
msgstr ""

#: keystone/token/providers/common.py:646
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/pki.py:48 keystone/token/providers/pkiz.py:30
msgid "Unable to sign token."
msgstr ""

#: keystone/token/providers/fernet/core.py:215
msgid ""
"This is not a v2.0 Fernet token. Use v3 for trust, domain, or federated "
"tokens."
msgstr ""

#: keystone/token/providers/fernet/token_formatters.py:83
msgid "This is not a recognized Fernet token"
msgstr ""

#: keystone/token/providers/fernet/token_formatters.py:246
#, python-format
msgid "This is not a recognized Fernet payload version: %s"
msgstr ""

#: keystone/trust/controllers.py:141
msgid "Redelegation allowed for delegated by trust only"
msgstr ""

#: keystone/trust/controllers.py:174
msgid "The authenticated user should match the trustor."
msgstr ""

#: keystone/trust/controllers.py:179
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:61
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed "
"range of [0..%(max_count)d]"
msgstr ""

#: keystone/trust/core.py:70
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr ""

#: keystone/trust/core.py:81
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr ""

#: keystone/trust/core.py:91
msgid "Some of requested roles are not in redelegated trust"
msgstr ""

#: keystone/trust/core.py:120
msgid "One of the trust agents is disabled or deleted"
msgstr ""

#: keystone/trust/core.py:139
msgid "remaining_uses must be a positive integer or null."
msgstr ""

#: keystone/trust/core.py:145
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than "
"allowed %(max_count)d"
msgstr ""

#: keystone/trust/core.py:152
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr ""

#: keystone/trust/core.py:162
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting"
" this parameter is advised."
msgstr ""

